import type { Product } from "@/types";

// Shared mock data for inventory and products modules
export const MOCK_PRODUCTS_WITH_STOCK: Product[] = [
  {
    id: "boxers-white",
    name: "Signature Boxer - White",
    description: "Premium comfort boxers in crisp white.",
    price: "US$45",
    priceNum: 45,
    tag: "Signature",
    collectionId: "boxers",
    stock: 120,
    lowStockThreshold: 20,
    images: [
      { id: "1", url: "/collections/boxers/boxersWhite.jpeg", isPrimary: true },
    ],
    colors: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "hoodie-black",
    name: "Classic Hoodie - Black",
    description: "The staple hoodie.",
    price: "US$85",
    priceNum: 85,
    tag: "Essential",
    collectionId: "hoodies",
    stock: 8,
    lowStockThreshold: 10,
    images: [
      {
        id: "2",
        url: "/collections/hoodies/hoodieBlackMan.jpg",
        isPrimary: true,
      },
    ],
    colors: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "bold-cap-black",
    name: "Bold Society Cap - Black",
    description: "Statement cap.",
    price: "US$55",
    priceNum: 55,
    tag: "Limited",
    collectionId: "headwear",
    stock: 5,
    lowStockThreshold: 10,
    images: [
      {
        id: "3",
        url: "/collections/headwear/boldSocietyCapBlack.jpg",
        isPrimary: true,
      },
    ],
    colors: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "outlaw-glasses",
    name: "Outlaw Shades",
    description: "Shield your eyes in style.",
    price: "US$75",
    priceNum: 75,
    tag: "Signature",
    collectionId: "sunglasses",
    stock: 22,
    lowStockThreshold: 15,
    images: [
      {
        id: "4",
        url: "/collections/glases/outlawGlasses1.jpg",
        isPrimary: true,
      },
    ],
    colors: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "track-set",
    name: "Movement Track Set",
    description: "Move with intention.",
    price: "US$95",
    priceNum: 95,
    tag: "Essential",
    collectionId: "tracks",
    stock: 3,
    lowStockThreshold: 10,
    images: [
      { id: "5", url: "/collections/tracks/track.jpg", isPrimary: true },
    ],
    colors: [],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-01T00:00:00Z",
  },
];
