export const queryKeys = {
  me: ["auth", "me"] as const,
  dashboard: ["dashboard"] as const,
  analytics: (from: string, to: string) => ["analytics", from, to] as const,
  collections: ["collections"] as const,
  products: (params?: object) => ["products", params] as const,
  product: (id: string) => ["products", id] as const,
  orders: (params?: object) => ["orders", params] as const,
  order: (id: string) => ["orders", id] as const,
  deliveryEvents: (orderId: string) =>
    ["orders", orderId, "delivery-events"] as const,
  customers: (params?: object) => ["customers", params] as const,
  customer: (id: string) => ["customers", id] as const,
  customerOrders: (id: string) => ["customers", id, "orders"] as const,
  reviews: (params?: object) => ["reviews", params] as const,
  bannerConfig: ["announcements", "config"] as const,
  bannerMessages: ["announcements", "messages"] as const,
  newsletter: (params?: object) => ["newsletter", params] as const,
  settings: ["settings"] as const,
  adminUsers: ["admin-users"] as const,
  search: (q: string) => ["search", q] as const,
  riders: (params?: object) => ["riders", params] as const,
  rider: (id: string) => ["riders", id] as const,
};
